version: '3.7'

services:
  app:
    container_name: 3dru_agenda_worker
    build: ./worker
    restart: always
    env_file:
      - "./worker/.env.dev"
    depends_on:
      - postgres

  postgres:
    container_name: 3dru_agenda_postgres
    image: postgres
    restart: always
    env_file:
      - "./vault/.env.dev"
    volumes:
      - "./vault/init.sql:/docker-entrypoint-initdb.d/init.sql"
      - "./vault/data:/data/postgres"
    ports:
      - "5432:5432"
